# Useful computations

- Matrix Multiplication
- Element wise operations
- Transposition
- Find
- max, sum, prod, ceil, floor, abs
- Trace
- Pseudoinverse

#### Some initializations

In [1]:
A = [1 2; 3 4; 5 6]
B = [11 12; 13 14; 15 16]
C = [1 1; 2 2]

A =

   1   2
   3   4
   5   6

B =

   11   12
   13   14
   15   16

C =

   1   1
   2   2



## Matrix multiplication

In [2]:
A * C

ans =

    5    5
   11   11
   17   17



## Vector or Matrix element wise operations

In [3]:
A .* B % <-- period (.) is usually used to indicate element wise operations

ans =

   11   24
   39   56
   75   96



In [4]:
A .^ 2

ans =

    1    4
    9   16
   25   36



In [5]:
1 ./ A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [6]:
v = [1; 2; 3]

1 ./ v

v =

   1
   2
   3

ans =

   1.00000
   0.50000
   0.33333



In [7]:
log(v)

ans =

   0.00000
   0.69315
   1.09861



In [8]:
exp(v)

ans =

    2.7183
    7.3891
   20.0855



In [9]:
abs([-1; 2; -3])

ans =

   1
   2
   3



In [10]:
-v % same as -1 * v

ans =

  -1
  -2
  -3



In [11]:
v + ones(length(v), 1)

ans =

   2
   3
   4



In [12]:
% or simply
v + 1

ans =

   2
   3
   4



## Transposition

In [13]:
A'

ans =

   1   3   5
   2   4   6



In [14]:
(A')'

ans =

   1   2
   3   4
   5   6



In [15]:
a = [1 15 2 .5]

a =

    1.00000   15.00000    2.00000    0.50000



## Find

In [16]:
help find

'find' is a built-in function from the file libinterp/corefcn/find.cc

 -- Built-in Function: IDX = find (X)
 -- Built-in Function: IDX = find (X, N)
 -- Built-in Function: IDX = find (X, N, DIRECTION)
 -- Built-in Function: [i, j] = find (...)
 -- Built-in Function: [i, j, v] = find (...)
     Return a vector of indices of nonzero elements of a matrix, as a
     row if X is a row vector or as a column otherwise.

     To obtain a single index for each matrix element, Octave pretends
     that the columns of a matrix form one long vector (like Fortran
     arrays are stored).  For example:

          find (eye (2))
            => [ 1; 4 ]

     If two inputs are given, N indicates the maximum number of elements
     to find from the beginning of the matrix or vector.

     If three inputs are given, DIRECTION should be one of "first" or
     "last", requesting only the first or last N indices, respectively.
     However, the indices are always returned in ascending order.

     If two 

In [17]:
find(a < 3) % each element of `a` is < 3

ans =

   1   3   4



### Magic Matrices

In [18]:
help magic

'magic' is a function from the file /usr/share/octave/4.0.3/m/special-matrix/magic.m

 -- Function File: magic (N)

     Create an N-by-N magic square.

     A magic square is an arrangement of the integers '1:n^2' such that
     the row sums, column sums, and diagonal sums are all equal to the
     same value.

     Note: N must be greater than 2 for the magic square to exist.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [19]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [20]:
[r, c] = find(A >= 7)

r =

   1
   3
   2

c =

   1
   2
   3



## Max value

In [21]:
A = magic(3)
a = [1 15 2 .5]

A =

   8   1   6
   3   5   7
   4   9   2

a =

    1.00000   15.00000    2.00000    0.50000



In [22]:
max(a)

ans =  15


In [23]:
[val ind] = max(a)

val =  15
ind =  2


In [24]:
max(A) % perform column wise operation

ans =

   8   9   7



In [25]:
max(A, [], 1) % column wise

ans =

   8   9   7



In [26]:
max(A, [], 2) % row wise

ans =

   8
   7
   9



###### Entire Matrix

In [27]:
max(max(A)) 

ans =  9


In [28]:
% turn into a column vector and apply max
max(A(:))

ans =  9


## More element wise operations

In [29]:
a < 3 % element wise comparison

ans =

   1   0   1   1



In [30]:
sum(a) % sum each element

ans =  18.500


In [31]:
prod(a) % multiply each element

ans =  15


In [32]:
floor(a) % round down each element

ans =

    1   15    2    0



In [33]:
ceil(a) % round up each element

ans =

    1   15    2    1



In [34]:
max(rand(3), rand(3))

ans =

   0.59376   0.29353   0.43380
   0.83083   0.95891   0.86848
   0.84632   0.93532   0.79315



#### Extracting the main diagonal

In [35]:
A = magic(9)

A =

   47   58   69   80    1   12   23   34   45
   57   68   79    9   11   22   33   44   46
   67   78    8   10   21   32   43   54   56
   77    7   18   20   31   42   53   55   66
    6   17   19   30   41   52   63   65   76
   16   27   29   40   51   62   64   75    5
   26   28   39   50   61   72   74    4   15
   36   38   49   60   71   73    3   14   25
   37   48   59   70   81    2   13   24   35



In [36]:
A .* eye(9)

ans =

   47    0    0    0    0    0    0    0    0
    0   68    0    0    0    0    0    0    0
    0    0    8    0    0    0    0    0    0
    0    0    0   20    0    0    0    0    0
    0    0    0    0   41    0    0    0    0
    0    0    0    0    0   62    0    0    0
    0    0    0    0    0    0   74    0    0
    0    0    0    0    0    0    0   14    0
    0    0    0    0    0    0    0    0   35



In [37]:
sum(sum(A .* eye(9))) % the sum of all diagonal entries

ans =  369


## Trace

In [38]:
trace(A) % i.e. the sum of main diagonal entries

ans =  369


In [39]:
flipud(eye(9))

ans =

Permutation Matrix

   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   1   0   0   0
   0   0   0   0   1   0   0   0   0
   0   0   0   1   0   0   0   0   0
   0   0   1   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0



In [40]:
sum(sum(A .* flipud(eye(9))))

ans =  369


## Pseudoinverse

In [41]:
help pinv

'pinv' is a built-in function from the file libinterp/corefcn/pinv.cc

 -- Built-in Function: pinv (X)
 -- Built-in Function: pinv (X, TOL)
     Return the pseudoinverse of X.

     Singular values less than TOL are ignored.

     If the second argument is omitted, it is taken to be

          tol = max (size (X)) * sigma_max (X) * eps,

     where 'sigma_max (X)' is the maximal singular value of X.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [42]:
p_inv = pinv(magic(3))

p_inv =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [43]:
p_inv * magic(3)

ans =

   1.00000   0.00000  -0.00000
  -0.00000   1.00000   0.00000
   0.00000   0.00000   1.00000

